#!/usr/bin/ruby

require 'socket' #=> true

#script to get IPs of systems from an input file 

#if none supplied request it
if ARGV.length < 1
  puts "Please enter a file"
  #puts "Usage: ruby MyScript.rb InputFile.csv SortedOutputFile.csv\n"
  input_file = gets
else
#get the filename from the command line
  input_file = ARGV[0]
end

my_domain = ARGV[1]


IO.foreach(input_file) {|line|
	my_host = line.chomp
	#puts line
	qualified_host = my_host + "." + my_domain
        #p qualified_host
	#p IPSocket::getaddress("#{qualified_host}")
	result = `host "#{qualified_host}"`
	p result.chomp

}

