#!/usr/bin/ruby

require 'socket' #=> true

#script to get IPs of systems from an input file 

#if none supplied request it
if ARGV.length < 1
  puts "Please enter a file"
  #puts "Usage: ruby MyScript.rb InputFile.csv SortedOutputFile.csv\n"
  input_file = gets
else
#get the filename from the command line
  input_file = ARGV[0]
end


IO.foreach(input_file) {|line|
	puts line
	#p IPSocket::getaddress("#{line}")
	p `host "#{line}.admdom.harpercollege.edu"`

}

