#!/usr/bin/ruby

#script to get IPs of systems from an input file 

#get the filename from the command line

#if none supplied request it


File.open(filename, "r") do |aFile|
# ... process the file


end

